import { el } from "./dom";
import type { Child, Props } from "./dom_types";

export function Fragment(_props?: Props | Child, ...children: Child[]): Child[] {
  return children;
}

export const div = (props?: Props<HTMLDivElement> | Child, ...children: Child[]) => el("div", props, ...children);
export const span = (props?: Props<HTMLSpanElement> | Child, ...children: Child[]) => el("span", props, ...children);
export const button = (props?: Props<HTMLButtonElement> | Child, ...children: Child[]) => el("button", props, ...children);
export const input = (props?: Props<HTMLInputElement>) => el("input", props);
export const textarea = (props?: Props<HTMLTextAreaElement> | Child, ...children: Child[]) => el("textarea", props, ...children);
export const select = (props?: Props<HTMLSelectElement> | Child, ...children: Child[]) => el("select", props, ...children);
export const option = (props?: Props<HTMLOptionElement> | Child, ...children: Child[]) => el("option", props, ...children);
export const label = (props?: Props<HTMLLabelElement> | Child, ...children: Child[]) => el("label", props, ...children);
export const form = (props?: Props<HTMLFormElement> | Child, ...children: Child[]) => el("form", props, ...children);
export const fieldset = (props?: Props<HTMLFieldSetElement> | Child, ...children: Child[]) => el("fieldset", props, ...children);
export const legend = (props?: Props<HTMLLegendElement> | Child, ...children: Child[]) => el("legend", props, ...children);
export const a = (props?: Props<HTMLAnchorElement> | Child, ...children: Child[]) => el("a", props, ...children);
export const img = (props?: Props<HTMLImageElement>) => el("img", props);
export const dialog = (props?: Props<HTMLDialogElement> | Child, ...children: Child[]) => el("dialog", props, ...children);
export const canvas = (props?: Props<HTMLCanvasElement> | Child, ...children: Child[]) => el("canvas", props, ...children);
export const ul = (props?: Props<HTMLUListElement> | Child, ...children: Child[]) => el("ul", props, ...children);
export const ol = (props?: Props<HTMLOListElement> | Child, ...children: Child[]) => el("ol", props, ...children);
export const li = (props?: Props<HTMLLIElement> | Child, ...children: Child[]) => el("li", props, ...children);
export const dl = (props?: Props<HTMLDListElement> | Child, ...children: Child[]) => el("dl", props, ...children);
export const dt = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("dt", props, ...children);
export const dd = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("dd", props, ...children);
export const h1 = (props?: Props<HTMLHeadingElement> | Child, ...children: Child[]) => el("h1", props, ...children);
export const h2 = (props?: Props<HTMLHeadingElement> | Child, ...children: Child[]) => el("h2", props, ...children);
export const h3 = (props?: Props<HTMLHeadingElement> | Child, ...children: Child[]) => el("h3", props, ...children);
export const h4 = (props?: Props<HTMLHeadingElement> | Child, ...children: Child[]) => el("h4", props, ...children);
export const h5 = (props?: Props<HTMLHeadingElement> | Child, ...children: Child[]) => el("h5", props, ...children);
export const h6 = (props?: Props<HTMLHeadingElement> | Child, ...children: Child[]) => el("h6", props, ...children);
export const p = (props?: Props<HTMLParagraphElement> | Child, ...children: Child[]) => el("p", props, ...children);
export const strong = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("strong", props, ...children);
export const em = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("em", props, ...children);
export const small = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("small", props, ...children);
export const section = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("section", props, ...children);
export const article = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("article", props, ...children);
export const nav = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("nav", props, ...children);
export const header = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("header", props, ...children);
export const footer = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("footer", props, ...children);
export const main = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("main", props, ...children);
export const aside = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("aside", props, ...children);
export const table = (props?: Props<HTMLTableElement> | Child, ...children: Child[]) => el("table", props, ...children);
export const thead = (props?: Props<HTMLTableSectionElement> | Child, ...children: Child[]) => el("thead", props, ...children);
export const tbody = (props?: Props<HTMLTableSectionElement> | Child, ...children: Child[]) => el("tbody", props, ...children);
export const tfoot = (props?: Props<HTMLTableSectionElement> | Child, ...children: Child[]) => el("tfoot", props, ...children);
export const tr = (props?: Props<HTMLTableRowElement> | Child, ...children: Child[]) => el("tr", props, ...children);
export const th = (props?: Props<HTMLTableCellElement> | Child, ...children: Child[]) => el("th", props, ...children);
export const td = (props?: Props<HTMLTableCellElement> | Child, ...children: Child[]) => el("td", props, ...children);
export const details = (props?: Props<HTMLDetailsElement> | Child, ...children: Child[]) => el("details", props, ...children);
export const summary = (props?: Props<HTMLElement> | Child, ...children: Child[]) => el("summary", props, ...children);
export const template = (props?: Props<HTMLTemplateElement> | Child, ...children: Child[]) => el("template", props, ...children);
