import type {
  AttributePrimitive,
  CommonProps,
  MaybeReactive,
} from "./domTypes";

export type SvgAttribute =
  | "alignmentBaseline"
  | "baselineShift"
  | "className"
  | "clipPath"
  | "clipRule"
  | "color"
  | "colorInterpolation"
  | "colorInterpolationFilters"
  | "colorRendering"
  | "cx"
  | "cy"
  | "d"
  | "display"
  | "dominantBaseline"
  | "fill"
  | "fillOpacity"
  | "fillRule"
  | "filter"
  | "floodColor"
  | "floodOpacity"
  | "focusable"
  | "fontFamily"
  | "fontSize"
  | "fontSizeAdjust"
  | "fontStretch"
  | "fontStyle"
  | "fontVariant"
  | "fontWeight"
  | "height"
  | "href"
  | "id"
  | "imageRendering"
  | "letterSpacing"
  | "lightingColor"
  | "markerEnd"
  | "markerMid"
  | "markerStart"
  | "mask"
  | "opacity"
  | "paintOrder"
  | "pathLength"
  | "points"
  | "preserveAspectRatio"
  | "r"
  | "rx"
  | "ry"
  | "shapeRendering"
  | "stopColor"
  | "stopOpacity"
  | "stroke"
  | "strokeDasharray"
  | "strokeDashoffset"
  | "strokeLinecap"
  | "strokeLinejoin"
  | "strokeMiterlimit"
  | "strokeOpacity"
  | "strokeWidth"
  | "tabindex"
  | "textAnchor"
  | "textDecoration"
  | "textRendering"
  | "transform"
  | "transformOrigin"
  | "vectorEffect"
  | "viewBox"
  | "visibility"
  | "width"
  | "wordSpacing"
  | "writingMode"
  | "x"
  | "x1"
  | "x2"
  | "xlink:href"
  | "xmlns"
  | "y"
  | "y1"
  | "y2";

export type SvgProps<E extends SVGElement = SVGElement> = CommonProps<E> & {
  [K in SvgAttribute]?: MaybeReactive<AttributePrimitive>;
};
